DROP SCHEMA IF EXISTS EASY;
CREATE SCHEMA IF NOT EXISTS EASY;
USE EASY;

-- SE CREA LA TABLA SUELDOS, QUE CONTIENE SUELDO BRUTO Y NETO DE TODOS LOS EMPLEADOS EL EASY
DROP TABLE IF EXISTS SUELDOS;
CREATE TABLE IF NOT EXISTS SUELDOS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    SUELDO_BRUTO decimal NOT NULL,
    SUELDO_NETO decimal NOT NULL,
	ID_ENCARGADO_SECTOR INT NOT NULL,
    ID_ASESOR INT NOT NULL,
    ID_ADMINISTRACION INT NOT NULL
);


-- SE CREA LA TABLA ASESOR
DROP TABLE IF EXISTS ASESOR;
CREATE TABLE IF NOT EXISTS ASESOR(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    DNI NUMERIC,
    TELEFONO VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(30) NOT NULL,
    ANTIGUEDAD NUMERIC,
    ID_SECTOR INT NOT NULL,
    ID_PRODUCTO INT NOT NULL
    );

    
-- SE CREA LA TABLA ADMINISTRACION
DROP TABLE IF EXISTS ADMINISTRACION;
CREATE TABLE IF NOT EXISTS ADMINISTRACION(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    ANTIGUEDAD VARCHAR(30),
    ID_ENCARGADO_SECTOR INT NOT NULL,
    ID_PROVEEDOR INT NOT NULL,
    ID_ASESOR INT NOT NULL
);



-- SE CREA LA TABLA DE ENCARGADO DE SECTOR
DROP TABLE IF EXISTS ENCARGADO_SECTOR;
CREATE TABLE IF NOT EXISTS ENCARGADO_SECTOR(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    DNI NUMERIC,
    TELEFONO VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(30) NOT NULL,
    ANTIGUEDAD NUMERIC
);

-- SE CREA LA TABLA SECTOR
DROP TABLE IF EXISTS SECTOR;
CREATE TABLE IF NOT EXISTS SECTOR(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    ID_ENCARGADO_SECTOR INT NOT NULL
);

DROP TABLE IF EXISTS PROVEEDOR;
CREATE TABLE IF NOT EXISTS PROVEEDOR(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RAZON_SOCIAL NUMERIC
);

-- SE CREA LA TABLA PRODUCTO
DROP TABLE IF EXISTS PRODUCTO;
CREATE TABLE IF NOT EXISTS PRODUCTO (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    CANTIDAD NUMERIC,
    ID_ASESOR INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_SECTOR INT NOT NULL
);

-- SE CREA LA TABLA CLIENTES
DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE IF NOT EXISTS CLIENTES (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30),
    TELEFONO VARCHAR(25),
    EMAIL VARCHAR(25),
    DIRECCION VARCHAR (25),
    ID_PRODUCTO INT NOT NULL,
    ID_ASESOR INT NOT NULL
);
